name: pet_insurance
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  carousel_slider: ^4.0.0
  html: ^0.15.4
  flutter_session_manager: ^1.0.3
  quickalert: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - Image/
